language: android
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
     #The BuildTools version used by your project
    - build-tools-25.0.1
    - android-25
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-25
    - extra-android-m2repository
    
  #licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
addons:
  sonarqube:
    token: 0a5619a9126f75efab72da9509b32be90719d906
    
script:
  #- ./gradlew build connectedCheck
  - sonar-scanner
