before_install:
    chmod +x gradlew
language: android
android:
    components:
    # The BuildTools version used by your project
    - build-tools-25.0.1
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository
