language: android
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

#android:
  #components:
    #- tools
    #- platform-tools
    # The BuildTools version used by your project
    #- build-tools-24.0.2
    #- android-22
    #- android-24
    
    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- sys-img-armeabi-v7a-android-24
    #- sys-img-armeabi-v7a-android-22
    #- extra-android-m2repository
    
  #licenses:
   # - '.+'
    
addons:
  sonarqube:
    token: 0a5619a9126f75efab72da9509b32be90719d906
    
script:
  - ./gradlew build connectedCheck
  - sonar-scanner
