before_install:
    chmod +x gradlew
language: android
android:
    components:
    # The BuildTools version used by your project
    - build-tools-24.0.3
    - android-24

    # Support library
    - extra-android-support
    - extra-android-m2repository
