before_install:
    chmod +x gradlew
language: android
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.0
    - android-25
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-24
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
